### PR TITLE
feat(repository): Support rpm-based linux distros

### PR DESCRIPTION
**Pull request by noelmcloughlin**
This PR adds support for [RPM-based distro repo](https://grafana.com/docs/installation/rpm/). BREAKING CHANGE: the variable 'pkg' was renamed 'pkg.name', update your pillars.  Verified on CentOS7
```
          ID: grafana-package-repo-install-pkgrepo-managed
    Function: pkgrepo.managed
        Name: grafana
      Result: True
     Comment: Configured package repo 'grafana'
     Started: 01:55:40.920248
    Duration: 36.173 ms
     Changes:   
              ----------
              repo:
                  grafana
----------
          ID: grafana-package-install-pkg-installed
    Function: pkg.installed
        Name: grafana
      Result: True
     Comment: The following packages were installed/updated: grafana
     Started: 01:55:40.956541
    Duration: 89291.515 ms
     Changes:   
              ----------
              dejavu-fonts-common:
                  ----------
                  new:
                      2.33-6.el7
                  old:
              dejavu-sans-fonts:
                  ----------
                  new:
                      2.33-6.el7
                  old:
              fontconfig:
                  ----------
                  new:
                      2.13.0-4.3.el7
                  old:
              fontpackages-filesystem:
                  ----------
                  new:
                      1.44-8.el7
                  old:
              gpg-pubkey.(none):
                  ----------
                  new:
                      168a1ea1-58138084,24098cb6-58875d52,352c64e5-52ae6884,7457ccd1-58071431,de57bfbe-53a9be98,f4a80eb5-53a7ff4b
                  old:
                      168a1ea1-58138084,352c64e5-52ae6884,7457ccd1-58071431,de57bfbe-53a9be98,f4a80eb5-53a7ff4b
              grafana:
                  ----------
                  new:
                      6.2.0-beta2
                  old:
              libfontenc:
                  ----------
                  new:
                      1.1.3-3.el7
                  old:
              urw-fonts:
                  ----------
                  new:
                      2.4-16.el7
                  old:
              xorg-x11-font-utils:
                  ----------
                  new:
                      1:7.5-21.el7
                  old:
----------
          ID: grafana-config-file-file-managed
    Function: file.managed
        Name: /etc/grafana/grafana.ini
      Result: True
     Comment: File /etc/grafana/grafana.ini updated
     Started: 01:57:10.252657
    Duration: 164.119 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,530 +1,7 @@
                  -##################### Grafana Configuration Example #####################
                  -#
                  -# Everything has defaults so you only need to uncomment things you want to
<< CUT >>

                  -
----------
          ID: grafana-service-running-service-running
    Function: service.running
        Name: grafana-server
      Result: True
     Comment: Service grafana-server has been enabled, and is running
     Started: 01:57:10.960623
    Duration: 602.27 ms
     Changes:   
              ----------
              grafana-server:
                  True
```
The Repo.
```
[vagrant@localhost ~]$ cat /etc/yum.repos.d/grafana.repo 
[grafana]
repo_gpgcheck=1
sslverify=1
name=grafana
gpgkey=https://packages.grafana.com/gpg.key
enabled=1
baseurl=https://packages.grafana.com/oss/rpm-beta
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
gpgcheck=1
# instructions from https://grafana.com/docs/installation/rpm/
```

### CODE REVIEW

**Comment by myii** [comment]
@noelmcloughlin Quick note, the [commit type](https://github.com/saltstack-formulas/template-formula/blob/9de820d71f13b3e0ddcb18b0436a99696eda997e/docs/CONTRIBUTING.rst#relationship-between-commit-type-and-version-bump) is `feat` rather than `feature`.

**Comment by noelmcloughlin** [comment]
> @noelmcloughlin Quick note, the [commit type](https://github.com/saltstack-formulas/template-formula/blob/9de820d71f13b3e0ddcb18b0436a99696eda997e/docs/CONTRIBUTING.rst#relationship-between-commit-type-and-version-bump) is `feat` rather than `feature`.

Thanks @myii  fixed.

**Comment by noelmcloughlin** [comment]
Hi @myii  
Why is sentence beginning ' BREAKING CHANGE: ..' unacceptable? 
I understood this format was documented but unit test does not like this.

**Comment by myii** [comment]
@noelmcloughlin `BREAKING CHANGE` is fine, the issue you've got is shown here:

* https://travis-ci.com/saltstack-formulas/grafana-formula/jobs/207251158#L497

Meaning:

```diff
-feat(repository): Support rpm-based linux distros
+feat(repository): support rpm-based linux distros
```

By the way, where are you using `BREAKING CHANGE`?

**Comment by noelmcloughlin** [comment]
Apologies. fonts can be misleading.  - I never saw the uppercase 'S' so assumed 'BREAKING CHANGE' was being complained of and removed it.

**Comment by noelmcloughlin** [comment]
Fixed the conflict. Thanks for reviewing @ myii

**Pull request merged**
