### PR TITLE
fix(macos): ensure group is correct for macos

### LINKED ISSUE #1: MacOS: group grafana is not available
This formula needs work for MacOS
```
          ID: grafana-config-file-file-managed
    Function: file.managed
        Name: /etc/grafana/grafana.ini
      Result: False
     Comment: Group grafana is not available
```

### PR DESCRIPTION
**Pull request by noelmcloughlin**
Resolves #1 and fixes service name too.

### CODE REVIEW

**Comment by myii** [comment]
@noelmcloughlin Just a quick note about the commit message:

```diff
-bugfix(macos): ensure group is correct for macos
+fix(macos): ensure group is correct for macos
```

A release will still be created because of the other `fix` commit but this `bugfix` one won't show up in the changelog or the release notes.  Unless you're planning to squash the commits anyway.

**Comment by noelmcloughlin** [comment]
> A release will still be created because of the other `fix` commit but this `bugfix` one won't show up in the changelog or the release notes. Unless you're planning to squash the commits anyway.

Thanks for explaining that. Squashing!!

**Review by vutny — APPROVED** [review]
LGTM

**Comment by noelmcloughlin** [comment]
Thanks @vutny and @myii

**Pull request merged**
