### PR TITLE
feat(macos): basic package and group handling

### PR DESCRIPTION
**Pull request by noelmcloughlin**
PR adding basic package & group handling (see https://github.com/saltstack/salt/issues/53325) on MacOS.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Resolves rendering error in #1

**Comment by noelmcloughlin** [comment]
Hi @myii I have updated this as well.

**Comment by myii** [comment]
@noelmcloughlin Great, just waiting for write access so we can request a review...

**Comment by myii** [comment]
@noelmcloughlin Done, I've also requested the review.

**Review by aboe76 — APPROVED** [review]
nice work @noelmcloughlin

**Comment by myii** [comment]
Fixed the `semantic-release` bot here as well, with reference to https://github.com/saltstack-formulas/prometheus-formula/pull/2#issuecomment-499278721.

**Pull request merged**
