### PR TITLE
fix(macro): remove unused 'concat_args' macro

### PR DESCRIPTION
**Pull request by noelmcloughlin**
This PR removes a macro declared but never invoked.

### CODE REVIEW

**Comment by myii** [comment]
@noelmcloughlin Let's get feedback from @alxwr -- maybe there was something in the pipeline to make use of this macro soon...

**Comment by noelmcloughlin** [comment]
Hi @alxwr could you give feedback

**Review by aboe76 — APPROVED** [review]
I don't see 'concat_args' used anywhere so I don't see an issue here.

**Comment by noelmcloughlin** [comment]
Thanks @aboe76 
The macro looks useful so I added here: https://github.com/saltstack-formulas/template-formula/pull/134#issuecomment-508204795

**Pull request merged**
